feat(client): api:client.update_listening_music/stop_listening_music
TWT233/khl.py pull request #116
Opened 2022-07-18 01:49 UTC by Aewait

feat(client): api:client.update_listening_music/stop_listening_music
fix(client): add data_type to api.client.stop_playing_game

2022-07-19 12:46 UTC, TWT233 requested changes

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +from ..interface import SlowModeTypes,SoftwareTypes
标点后面少了个空格

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +    async def stop_playing_game(self,data_type: int = 1):
ditto

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +    async def update_listening_music(self, music_name:str,singer:str,software:Union[str, SoftwareTypes], data_type: int = 2):
ditto

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +    async def stop_playing_game(self,data_type: int = 1):
其实这里不用 data type 参数了，因为函数名就包含了这个语义，留在这里反而有歧义

client.stop_playing_game() 同理

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +    async def update_listening_music(self, music_name:str,singer:str,software:Union[str, SoftwareTypes], data_type: int = 2):
data type 也不用了

2022-07-19 12:46 UTC, TWT233 commented on khl/bot/bot.py
> +    async def stop_listening_music(self,data_type: int = 2):
ditto

2022-07-19 12:46 UTC, TWT233 commented on khl/client.py
> +from .interface import AsyncRunnable, MessageTypes, SlowModeTypes,SoftwareTypes
format ditto

2022-07-19 12:46 UTC, TWT233 commented on khl/client.py
> +    async def stop_playing_game(self,data_type:int):
这里的 data type 已经不用了（如前所述），直接往 exec_req 里传 1 就好

2022-07-19 12:46 UTC, TWT233 commented on khl/client.py
> +    async def stop_listening_music(self,data_type:int):
同上，传 2 就好

2022-07-19 13:44 UTC, Aewait commented
添加一个测试截图
![test](https://img.kookapp.cn/assets/2022-07/ZsD7feoalW0ug0n5.png)

2022-07-21 03:32 UTC, TWT233 approved these changes
LGTM

2022-07-21 03:32 UTC, merged