添加了fetch_category方法，补全了ChannelCategory类中的方法
TWT233/khl.py pull request #119
Opened 2022-07-26 06:18 UTC by DeeChael

Bot和Client类添加了fetch_category方法
ChannelCategory类添加了update方法和操作用户和角色权限的方法
补全了API

**！已测试！**

2022-07-26 07:00 UTC, DeeChael commented
这个commitlint我想摆烂

2022-07-26 17:33 UTC, TWT233 commented
commitlint算是开源社区中比较通用的commit message rule了，学一下挺有好处的

2022-07-28 10:52 UTC, DeeChael commented
Rebased

2022-07-30 04:57 UTC, TWT233 requested changes

2022-07-30 04:57 UTC, TWT233 commented on khl/guild.py
> +class Invite(Requestable):
cardmessage里面还有个invite，虽然card是外围模块，地位会低一点，不过这里确实可以换个名字，比如InviteLink

2022-07-30 04:58 UTC, TWT233 commented
这里有个代码重复的问题，我觉得可以抽象东西出来，你看看怎么做好

2022-07-30 15:02 UTC, DeeChael commented on khl/guild.py
> +    async def fetch_permission(self, force_update: bool = True) -> ChannelPermission:
那放哪个里面，guild or channel?

2022-07-30 17:55 UTC, TWT233 commented on khl/guild.py
> +    async def fetch_permission(self, force_update: bool = True) -> ChannelPermission:
也可以的，你看着办！

2022-08-03 14:23 UTC, TWT233 requested changes

2022-08-03 14:23 UTC, TWT233 commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
channel里没有master id这个字段吧，好像还有一些其他字段也没有，还是得写一点出来

2022-08-03 14:23 UTC, TWT233 commented on khl/guild.py
> +        raise TypeError('now there is no ChannelCategory, *hey dude we have a pkg from future*')
现在已经有channel category了，所以应该是提示不能往category里发消息

2022-08-03 14:25 UTC, DeeChael commented on khl/guild.py
> +        raise TypeError('now there is no ChannelCategory, *hey dude we have a pkg from future*')
这个我直接照搬的PublicVoiceChannel

2022-08-03 14:30 UTC, DeeChael commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
https://developer.kookapp.cn/doc/http/channel#%E8%8E%B7%E5%8F%96%E9%A2%91%E9%81%93%E8%AF%A6%E6%83%85
接口会返回master_id
https://developer.kookapp.cn/doc/objects#%E9%A2%91%E9%81%93%20Channel
但是Objects没说

2022-08-03 14:33 UTC, TWT233 commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
其实现在khl.py的PublicChannel是没有带这个字段的，这里的问题得问问波波他们了，感觉是文档不对

2022-08-03 14:33 UTC, TWT233 commented on khl/guild.py
> +        raise TypeError('now there is no ChannelCategory, *hey dude we have a pkg from future*')
嗯，可以改改的

2022-08-03 14:46 UTC, DeeChael commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
还有个问题
如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错
所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里
这样该如何解决呢

2022-08-05 02:06 UTC, DeeChael commented
还有个问题
如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错
所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里
这样该如何解决呢

2022-08-09 14:20 UTC, TWT233 commented
> 还有个问题 如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错 所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里 这样该如何解决呢

我也考虑过，不过 channel category 其实是只有在 guild 才有的东西，而 channel.py 里的东西应该是只限定描述单个 channel

2022-08-10 10:24 UTC, DeeChael commented
> > 还有个问题 如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错 所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里 这样该如何解决呢
> 
> 我也考虑过，不过 channel category 其实是只有在 guild 才有的东西，而 channel.py 里的东西应该是只限定描述单个 channel

那public_channel_category就别创建category了吧，稍稍修改一下update_channel方法就行了

2022-08-10 10:38 UTC, DeeChael commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
所以该如何解决呢

2022-08-10 13:21 UTC, TWT233 commented
> > > 还有个问题 如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错 所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里 这样该如何解决呢
> > 
> > 
> > 我也考虑过，不过 channel category 其实是只有在 guild 才有的东西，而 channel.py 里的东西应该是只限定描述单个 channel
> 
> 那public_channel_category就别创建category了吧，稍稍修改一下update_channel方法就行了

public_channel_factory吗

2022-08-10 13:22 UTC, DeeChael commented
> > > > 还有个问题 如果想要public_channel_factory可以创建ChannelCategory就会因为导入的问题导致报错 所以在考虑要不要把ChannelCategory移到channel.py里面，但是这样很多机器人就得改代码里 这样该如何解决呢
> > > 
> > > 
> > > 我也考虑过，不过 channel category 其实是只有在 guild 才有的东西，而 channel.py 里的东西应该是只限定描述单个 channel
> > 
> > 
> > 那public_channel_category就别创建category了吧，稍稍修改一下update_channel方法就行了
> 
> public_channel_factory吗

什么

2022-08-10 13:43 UTC, TWT233 commented
> 那public_channel_category就别创建category了吧，稍稍修改一下update_channel方法就行了

这句里的public_channel_category是不是public_channel_factory

2022-08-10 13:44 UTC, DeeChael commented
> > 那public_channel_category就别创建category了吧，稍稍修改一下update_channel方法就行了
> 
> 这句里的public_channel_category是不是public_channel_factory

kusa，打错了

2022-08-19 08:03 UTC, TWT233 commented on khl/guild.py
> -        self.master_id = kwargs.get('master_id')
波波咋说的，我去翻翻

2022-12-10 10:07 UTC, closed without merging