feat(Message, Client): add update() method and fetch_public_message() method
TWT233/khl.py pull request #125
Opened 2022-08-17 02:39 UTC by DeeChael

在Message类里添加了update()方法用来更新消息
Client中添加了update_message()方法
Client中还添加了fetch_public_message()方法，可以通过msg_id获取一个PublicMessage对象

2022-08-19 07:33 UTC, TWT233 requested changes

2022-08-19 07:33 UTC, TWT233 commented on khl/client.py
> +        return PublicMessage(**(await self.gate.exec_req(api.Message.view(msg_id=msg_id))), _gate_=self.gate)
message/view 返回的数据格式很奇怪，我记得不能直接丢给PublicMessage构造

而且也推荐拆成两个pr，现在这个pr做了两件事

2022-08-19 07:33 UTC, TWT233 commented on khl/client.py
> +        params = {'msg_id': msg if isinstance(msg, str) else msg.id, 'content': content if isinstance(content, str) else json.dumps(content)}
0.3.0加了个工具，专门用来解union里的id，能简化一些代码，是放在.util里的unpack_id

2022-08-19 07:33 UTC, TWT233 commented on khl/message.py
> +        if self.type is not MessageTypes.CARD and isinstance(content, List):
是不是不用加这个校验，如果不是card还update成list的话，直接发marshal之后的list也符合预期

2022-08-19 07:33 UTC, TWT233 commented on khl/message.py
> +        if self.type is not MessageTypes.CARD and isinstance(content, List):
我懂了，是不是pylint说dup了

2022-08-19 07:33 UTC, TWT233 commented on khl/message.py
> +    async def update(self, content: Union[str, List], quote: str = None, temp_target_id: str = None):
私聊不能temp target id，如果要兼容接口的话推荐改名下划线

不过这里的官方接口也有点问题，是不太方便抽象

2022-08-19 07:33 UTC, TWT233 commented on khl/message.py
> +        if self.type is not MessageTypes.CARD and isinstance(content, List):
ditto.

2022-08-19 13:32 UTC, DeeChael commented on khl/message.py
> +    async def update(self, content: Union[str, List], quote: str = None, temp_target_id: str = None):
话说官方接口也不给私聊做临时更新的功能
临时更新挺有用的

2022-08-19 13:33 UTC, DeeChael commented on khl/client.py
> +        params = {'msg_id': msg if isinstance(msg, str) else msg.id, 'content': content if isinstance(content, str) else json.dumps(content)}
好

2022-08-19 13:34 UTC, DeeChael commented on khl/message.py
> +        if self.type is not MessageTypes.CARD and isinstance(content, List):
那我直接删了？

2022-08-24 14:49 UTC, TWT233 commented on khl/message.py
> +    async def update(self, content: Union[str, List], quote: str = None, temp_target_id: str = None):
因为私聊不能发临时消息吧

2022-08-24 14:49 UTC, TWT233 commented on khl/message.py
> +        if self.type is not MessageTypes.CARD and isinstance(content, List):
可以的

2022-11-22 04:35 UTC, closed without merging