修正创建分组时导致的错误
TWT233/khl.py pull request #167
Opened 2022-11-26 12:39 UTC by modcrafts

问题复现:
```
msg.ctx.guild.create_channel("分类", type=ChannelTypes.CATEGORY)
```

2022-11-26 12:50 UTC, modcrafts commented on khl/guild.py
> +                return ChannelCategory(**(await self.gate.exec_req(api.Channel.create(**params))), _gate_=self.gate)
直接按照 [channel.py](https://github.com/TWT233/khl.py/blob/main/khl/channel.py) 中的方法返回
未在 `channel.py` 中添加是因为会造成 `circular import`

2022-11-26 14:13 UTC, TWT233 requested changes

2022-11-26 14:16 UTC, modcrafts commented on khl/guild.py
> +                return ChannelCategory(**(await self.gate.exec_req(api.Channel.create(**params))), _gate_=self.gate)
我觉得二合一更好
因为 KOOK 官方接口就是二合一的
(刚开始看到这个项目，一些接口拆的到处都是让我有点懵，需要花些时间理解)

2022-11-26 14:18 UTC, TWT233 commented on khl/guild.py
> +                return ChannelCategory(**(await self.gate.exec_req(api.Channel.create(**params))), _gate_=self.gate)
欸 我觉得二合一不是很好用，因为会有语义杂糅的问题

2022-11-26 14:21 UTC, modcrafts commented on khl/guild.py
> +                return ChannelCategory(**(await self.gate.exec_req(api.Channel.create(**params))), _gate_=self.gate)
`delete_channel()` 怎么办，这个是通用的

2022-11-27 11:36 UTC, TWT233 commented on khl/guild.py
> +                return ChannelCategory(**(await self.gate.exec_req(api.Channel.create(**params))), _gate_=self.gate)
那可以也写一个 `delete_category()`，简单做成 alias 就行

2022-12-08 13:52 UTC, TWT233 commented
在 #173 中解决了，closed

2022-12-08 13:52 UTC, closed without merging