feat(channel): list channel messages
TWT233/khl.py pull request #182
Opened 2022-12-13 14:24 UTC by Leezj9671

增加了获取频道内信息的功能

2022-12-13 17:01 UTC, TWT233 commented
ack，明天看看

2022-12-13 17:01 UTC, TWT233 commented
不过好像ci没过，修修看？

2022-12-14 13:39 UTC, Leezj9671 commented
```
ImportError: cannot import name 'PublicMessage' from partially initialized module 'khl' (most likely due to a circular import) (miniconda3\envs\kook_robot\lib\site-packages\khl.py-0.3.11-py3.10.egg\khl\__init__.py)
```

import了Message对象会导致循环引用的问题，什么样的方式来调用会比较合适

2022-12-22 05:32 UTC, TWT233 commented
对，这里是之前设计有问题，层次不太对（计划是0.4.0改），那先保持这个形式提供能力吧

2022-12-22 05:33 UTC, TWT233 requested changes

2022-12-22 05:33 UTC, TWT233 commented on khl/_types.py
> +class MessageFlagMode(Enum):
需要在__init__.py里面导出一下方便用

2022-12-25 04:30 UTC, TWT233 approved these changes
LGTM

2022-12-25 04:31 UTC, merged