feat: add simple ratelimit control
TWT233/khl.py pull request #217
Opened 2023-10-21 15:28 UTC by hank9999

add simple ratelimit control

默认启用速率控制，如需禁用则需要手动构建HTTPRequester传入参数ratelimit=False 然后传入Bot
```python
cert = Cert(token=token)
http_request = HTTPRequester(cert=cert, ratelimit=True)
bot = Bot(cert=cert, out=http_request)
```

2023-11-03 14:36 UTC, TWT233 requested changes

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +        self._ratelimit = self.RateLimit()
naming:

作为一个组件，用名词更好
```suggestion
        self._ratelimiter = self.RateLimiter()
```

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +        self.ratelimit = ratelimit
看起来是一个flag，那么我推荐用 self._ratelimit is None 来兼做该flag的功能，比较简洁也足够自足

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +        if self.ratelimit:
extract func:

一般写出来缩进的时候就可以试试抽提函数，比如这里就可以抽提成一个 `wait_for_rate()`

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +            if self.ratelimit and 'X-Rate-Limit-Limit' in res.headers:
extract func:

ditto. `extract_xrate_header()`

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +            self._ratelimit_info: Dict[str, HTTPRequester.RateLimit.RateLimitData] = {}
这里是有读写冲突的，还是要加个锁比较安全，虽然一般都是单线程的async event loop

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +            delay = self._ratelimit.get_delay(bucket)
`get_delay`中可以内含一个`get_bucket`，这样API会更好理解

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +            return int(delay * 1000) / 1000  # keep three-digit decimal
相信asyncio，这里不用操心小数问题的

2023-11-03 14:36 UTC, TWT233 commented on khl/requester.py
> +                return self._ratelimit_info[bucket].reset * 1000
不用*1000，单位不是s吗

2023-11-03 17:50 UTC, hank9999 commented on khl/requester.py
> +            delay = self._ratelimit.get_delay(bucket)
delay 是由 bucket 获取的, 不是由 route 获取的 感觉分离比较好

2023-11-06 03:27 UTC, TWT233 requested changes

2023-11-06 03:27 UTC, TWT233 commented on khl/ratelimiter.py
> +    async def wait_for_rate(self, route):
可以试试把 `wait_for_rate()` 和 `update()`放到顶上

因为读代码一般都是从上往下读，一开始读的时候可能还不太了解具体的实现方法
所以先给出顶层的、暴露给外部的接口，有助于快速了解实现的大体思路，然后再往下跳转到具体细节看，会好理解一些

2023-11-06 04:47 UTC, hank9999 commented on khl/ratelimiter.py
> +    async def wait_for_rate(self, route):
好的 谢谢TWT老师

2023-11-06 06:51 UTC, TWT233 approved these changes
LGTM

2023-11-06 06:51 UTC, TWT233 commented
晚上我测测看

2023-11-06 06:53 UTC, hank9999 commented
> 晚上我测测看

好的，麻烦老师了，我这边测试的时候能稳定住速率

2023-11-07 13:09 UTC, merged