添加消息的引用内容
TWT233/khl.py pull request #218
Opened 2023-11-08 04:57 UTC by DancingSnow0517

现在可以直接在 `Message` 获取引用内容

```python
# 先判断 quote 是否非 None, None 代表消息不存在引用
if msg.quote:
    # 引用原文的 msg_id
    print(msg.quote.id)
    # 引用原文的内容
    print(msg.quote.content)
    # 引用原文的作者id
    print(msg.quote.author.id)
```

2023-11-09 13:13 UTC, TWT233 requested changes

2023-11-09 13:13 UTC, TWT233 commented on khl/message.py
> +            self._quote = PublicQuoteMessage(**self.extra['quote'], _gate_=self.gate, _lazy_loaded_=True)
```suggestion
            self._quote = PrivateQuoteMessage(**self.extra['quote'], _gate_=self.gate, _lazy_loaded_=True)
```

2023-11-09 13:13 UTC, TWT233 commented on khl/message.py
> +class QuoteMessage(Requestable, ABC):
naming: 推荐用 `QuotedMessage`

2023-11-09 13:50 UTC, DancingSnow0517 commented on khl/message.py
> +            self._quote = PublicQuoteMessage(**self.extra['quote'], _gate_=self.gate, _lazy_loaded_=True)
fixed

2023-11-12 01:24 UTC, TWT233 approved these changes
LGTM

2023-11-12 01:25 UTC, merged