fix(Guild): `guild-role/update` api use `role_id` instead of `id`
TWT233/khl.py pull request #223
Opened 2023-12-23 21:30 UTC by hank9999

参考: https://developer.kookapp.cn/doc/http/guild-role#更新服务器角色

2024-01-18 06:10 UTC, TWT233 requested changes

2024-01-18 06:10 UTC, TWT233 commented on khl/guild.py
> +        args = vars(new_role)
这么说来的话，更推荐改Role

现在想到的实现是把 `Role.id` 更名为 `Role.role_id`，然后提供一个 `Role.id()` 的 getter&setter

2024-01-18 06:10 UTC, TWT233 commented on khl/guild.py
> +        args = vars(new_role)
这样的话兼容性和效果都可以

2024-01-18 08:51 UTC, hank9999 commented on khl/guild.py
> +        args = vars(new_role)
@TWT233 修改已提交

2024-01-18 09:32 UTC, TWT233 commented
解下pylint的问题就好

2024-01-19 06:37 UTC, TWT233 approved these changes
LGTM

2024-01-19 06:37 UTC, merged