feature(role): add has_permission method
TWT233/khl.py pull request #73
Opened 2022-04-19 04:18 UTC by DancingSnow0517

添加权限的对应掩码解析
在 ``Role`` 类的 ``has_permission`` 方法, 返回一个 ``bool``
``bitValue`` 值见 [权限说明](https://developer.kaiheila.cn/doc/http/guild-role#%E6%9D%83%E9%99%90%E8%AF%B4%E6%98%8E)

2022-04-19 12:16 UTC, TWT233 requested changes

2022-04-19 12:16 UTC, TWT233 commented on khl/role.py
> +    def _perm_to_bit(self, count=28) -> str:
性能有点问题的，不需要转成[]str：
```py
def has_permission(perm: int, offset: int) -> bool:
    return perm & (1 << offset) != 0


permissions = 0xaaaaaaaa
offset_admin = 9

print(has_permission(permissions, offset_admin)) # True
```

2022-04-19 12:29 UTC, DancingSnow0517 commented
fixed

2022-04-20 07:09 UTC, TWT233 approved these changes
lgtm

2022-04-20 07:09 UTC, merged