implement `channel/update` api
TWT233/khl.py pull request #78
Opened 2022-05-09 10:24 UTC by DancingSnow0517

doc: [channel/update](https://developer.kaiheila.cn/doc/http/channel#%E7%BC%96%E8%BE%91%E9%A2%91%E9%81%93)

2022-05-10 02:40 UTC, TWT233 requested changes
有一个接口设计问题

2022-05-10 02:40 UTC, TWT233 commented on khl/channel.py
> +        #     params['slow_mode'] = slow_mode
```suggestion
        # slow mode is not supported by khl backend now, thus it is disabled
        # if slow_mode is not None:
        #     params['slow_mode'] = slow_mode
```

2022-05-10 02:40 UTC, TWT233 commented on khl/channel.py
> +    @abstractmethod
这个是PublicChannel限定的方法，不应该定义在Channel这个抽象接口类中

2022-05-10 02:40 UTC, TWT233 commented on khl/client.py
> +        if slow_mode is not None:
这里应该关掉

2022-05-10 02:40 UTC, TWT233 commented on khl/client.py
> +    async def update_channel(self, channel_id: str, name: str = None, topic: str = None, slow_mode: str = None) -> PublicChannel:
duplicated code

https://github.com/TWT233/khl.py/pull/78/files#diff-947548fb30783dbbe5995dc3e087e21fcc888a73e632087c8c39bc40b0166cd4R140

2022-05-10 02:40 UTC, TWT233 commented on khl/client.py
> +    async def update_channel(self, channel_id: str, name: str = None, topic: str = None, slow_mode: str = None) -> PublicChannel:
另一方面来说，其实bot可以直接用channel里定义的方法的，也不是说一定要写在client里，就像`Bot.send()`一样

2022-05-10 02:40 UTC, TWT233 commented on khl/bot/bot.py
> +    async def update_channel(self, channel_id: str, name: str = None, topic: str = None) -> PublicChannel:
可以做一下channel_id和Channel的兼容

2022-05-10 02:40 UTC, TWT233 commented on khl/bot/bot.py
> +
```suggestion
    async def update_channel(self,
                             channel: Union[PublicChannel, str],
                             name: str = None,
                             topic: str = None) -> PublicChannel:
        """update channel's settings"""
        channel_id = channel if isinstance(channel, str) else channel.id
        return await self.client.update_channel(channel_id, name, topic)
```

2022-05-10 04:25 UTC, DancingSnow0517 commented on khl/client.py
> +        if slow_mode is not None:
khl fixed it

2022-05-10 09:38 UTC, DancingSnow0517 commented on khl/client.py
> +    async def update_channel(self, channel_id: str, name: str = None, topic: str = None, slow_mode: str = None) -> PublicChannel:
但想用频道id进行修改，那改怎么做

2022-05-29 07:12 UTC, TWT233 requested changes
还有几个comments没有resolve

2022-05-29 08:38 UTC, DancingSnow0517 commented on khl/channel.py
> +
晚点来改，高考完先

2022-05-29 08:39 UTC, TWT233 commented on khl/channel.py
> +
吼 加油鸭

2022-06-09 05:21 UTC, TWT233 approved these changes
LGTM

2022-06-09 05:21 UTC, merged