feature(guild): add fetch_joined_channel method
TWT233/khl.py pull request #82
Opened 2022-05-28 06:05 UTC by DeeChael

implemented: [channel-user/get-joined-channel](https://developer.kaiheila.cn/doc/http/channel-user#%E6%A0%B9%E6%8D%AE%E7%94%A8%E6%88%B7id%E5%92%8C%E6%9C%8D%E5%8A%A1%E5%99%A8id%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E6%89%80%E5%9C%A8%E8%AF%AD%E9%9F%B3%E9%A2%91%E9%81%93)

2022-05-29 07:21 UTC, TWT233 reviewed
thanks for PR, but the code can be simplified with helpers

btw the commit message linter ci fails

2022-05-29 07:21 UTC, TWT233 commented on khl/guild.py
> +        response = await self.gate.exec_req(api.ChannelUser.getJoinedChannel(page=page, page_size=page_size, guild_id=self.id, user_id=user.id))
there is a native paged req helper: `gate.exec_pagination_req()` which may make this work easier

2022-05-29 07:21 UTC, TWT233 commented on khl/guild.py
> +        response = await self.gate.exec_req(api.ChannelUser.getJoinedChannel(page=page, page_size=page_size, guild_id=self.id, user_id=user.id))
FYI: `Guild.list_user()/fetch_roles()` is an usage example for `exec_pagination_req()`

2022-05-30 02:12 UTC, TWT233 requested changes
there may be a better approach with a higher level helper

2022-06-02 13:54 UTC, DeeChael commented
> thanks for PR, but the code can be simplified with helpers
> 
> btw the commit message linter ci fails

我看之前的commits里有用过feature啊

2022-06-02 15:36 UTC, TWT233 commented
> > thanks for PR, but the code can be simplified with helpers
> > btw the commit message linter ci fails
> 
> 我看之前的commits里有用过feature啊 已经改好了，但不知道怎么commit了

应该用 feat，以前还没commit lint所以我没注意就合进去了吧（

2022-06-03 02:16 UTC, DeeChael commented
> 我看好像没改？是不是被merge覆盖了

还没push呢 XD

2022-06-05 04:24 UTC, TWT233 commented
看起来是最开始的commit没过：
```
input: feature(guild): add fetch_joined_channel method
✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

2022-06-06 10:03 UTC, DeeChael commented
> 看起来是最开始的commit没过：
> 
> ```
> input: feature(guild): add fetch_joined_channel method
> ✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
> ✖   found 1 problems, 0 warnings
> ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> ```

那怎么处理？

2022-06-09 05:23 UTC, TWT233 commented
> > 看起来是最开始的commit没过：
> > ```
> > input: feature(guild): add fetch_joined_channel method
> > ✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
> > ✖   found 1 problems, 0 warnings
> > ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> > ```
> 
> 那怎么处理？

这里是 `feature(guild): add fetch_joined_channel method` 中开头的 feature 应该换成 feat，我一般会用 rebase 来改 commit message（同时可以顺便 squash 下）

2022-06-11 10:57 UTC, DeeChael commented
> > > 看起来是最开始的commit没过：
> > > ```
> > > input: feature(guild): add fetch_joined_channel method
> > > ✖   type must be one of [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
> > > ✖   found 1 problems, 0 warnings
> > > ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
> > > ```
> > 
> > 
> > 那怎么处理？
> 
> 这里是 `feature(guild): add fetch_joined_channel method` 中开头的 feature 应该换成 feat，我一般会用 rebase 来改 commit message（同时可以顺便 squash 下）

整半天不会整，放弃了，我直接重开pull request得了

2022-06-11 11:13 UTC, closed without merging