Role fix
TWT233/khl.py pull request #92
Opened 2022-06-18 06:27 UTC by DancingSnow0517

`roles` is actually a List[int]
add `fetch_roles` method to get the user roles in this guild

2022-06-18 06:28 UTC, DancingSnow0517 commented
草，这个commit检查一定得是feat不能feature吗

2022-06-19 13:41 UTC, TWT233 requested changes

2022-06-19 13:43 UTC, DancingSnow0517 commented on khl/user.py
> +    async def fetch_roles(self, guild_id: str) -> List[Role]:
拿给guildUser加个属性guild_id?

2022-06-19 13:45 UTC, TWT233 commented on khl/user.py
> +    async def fetch_roles(self, guild_id: str) -> List[Role]:
我的想法是把 roles 搬到 GuildUser 里，然后把 GuildUser 搬到 guild.py 里，GuildUser可以加一个属性guild/guild_id

2022-06-19 15:13 UTC, TWT233 approved these changes
LGTM

2022-06-19 15:22 UTC, merged